---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Configure unattended-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'
  notify: restart unattended-upgrades
