---
- name: Install required packages
  apt:
    name:
      - curl
      - wget
    state: present

- name: Install Netdata (official script)
  shell: |
    curl -fsSL https://get.netdata.cloud/kickstart.sh | bash -s -- --non-interactive
  args:
    executable: /bin/bash
  become: true

- name: Enable and start Netdata
  systemd:
    name: netdata
    state: started
    enabled: yes
  ignore_errors: yes
