---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Reset UFW rules
  ufw:
    state: reset

- name: Allow SSH
  ufw:
    rule: allow
    name: ssh

- name: Enable UFW
  ufw:
    state: enabled
    direction: incoming
    policy: deny
