---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Reset UFW rules
  ufw:
    state: reset

- name: Allow SSH on port 22
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
    direction: incoming
    policy: deny
