---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Create fail2ban configuration
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban

- name: Enable and start fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes
    daemon_reload: yes
  ignore_errors: yes
